Update patch set 1
Patch Set 1:

If I try:

$ buck test --all

I gen an error:
...
NameError: global name 'genfile' is not defined

I don't find the 'genfile' any where in the server-config plugin and it also doesn't exist in Gerrit's source code.

What am I doing wrong?

Patch-set: 1