Update patch set 2
Patch Set 2:

It failed to build because of one of the java files

bazel paladox@gerrit-test:~/gerrit$ bazel build plugins/server-config
WARNING: Sandboxed execution is not supported on your system and thus hermeticity of actions cannot be guaranteed. See http://bazel.build/docs/bazel-user-manual.html#sandboxing for more information. You can turn off this warning via --ignore_unsupported_sandboxing.
INFO: Found 1 target...
ERROR: /home/paladox/gerrit/plugins/server-config/BUILD:9:1: Java compilation in rule '//plugins/server-config:server-config__plugin' failed: Worker process sent response with exit code: 1.
plugins/server-config/src/main/java/com/googlesource/gerrit/plugins/serverconfig/ServerConfigServlet.java:172: error: incompatible types: Multimap<String,Object> cannot be converted to ListMultimap<String,?>
    auditService.dispatch(new AuditEvent(sessionId, who, what, when, params, null));
                                                                     ^Note: Some messages have been simplified; recompile with -Xdiags:verbose to get full outpuTarget //plugins/server-config:server-config failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 80.514s, Critical Path: 68.90s

This is the change https://github.com/gerrit-review/gerrit/commit/484da493b3a4585bae3dd68e4de4fc2166dbcd12

@David Ostrovsky him not sure how to fix the java file so it can build successfully.

Patch-set: 2
Reviewer: Gerrit User 1029953 <1029953@173816e5-2b9a-37c3-8a2e-48639d4f1153>